### ISSUE TITLE
requires modrinth maven

### ISSUE THREAD

**Issue by NyakoFox** [TropheusJ/milk-lib#7]
looks like the mod adds a bunch of mods in the dev environment, so i cant build my project without adding the modrinth maven

could there be a way to disable the extra mods? i have my own dev env setup

**Comment by TropheusJ** [comment]
They shouldn’t be pulled in, not sure why they are. Include it with transitive set to false, and include [dripstone fluid lib](https://github.com/TropheusJ/milk-lib/blob/349906a422039bbd04a208b45f0965d0452b0490/build.gradle#L49), the only dependency, manually.

**Comment by TropheusJ** [comment]
can't reproduce, I think this was the case with old versions. make sure you're up to date.
