### ISSUE TITLE
[1.19.2] Crash ChunkManager

### ISSUE THREAD

**Issue by itsdinkd** [TropheusJ/milk-lib#8]
https://mclo.gs/CzgcOUv 

I believe its from milk lib from what is reported in the stack trace. This occurred on a dedicated server

**Comment by TropheusJ** [comment]
if this wasn't a 1-off, it should now be impossible

**Comment by itsdinkd** [comment]
It's happened quite a bit. Still happens. I can provide logs when I'm back
home
